"""Add medications and chronic conditions to User model

Revision ID: 1088a68388e3
Revises: 
Create Date: 2025-05-04 17:58:06.208150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1088a68388e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('medications', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('chronic_conditions', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('progress_notes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'chronic_conditions')
    op.drop_column('users', 'medications')
    # ### end Alembic commands ###
